version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r backend/requirements.txt
  build:
    commands:
      - echo "Building the Lambda function..."
      - mkdir -p dist
      - cd lambda
      - zip -r ../dist/function.zip .
      - cd ..
  post_build:
    commands:
      - echo "Deploying the Lambda function..."
      - aws lambda update-function-code --function-name RouterLambda --zip-file fileb://dist/function.zip
artifacts:
  files:
    - 'function.zip'
  base-directory: dist