AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API Gateway connected to a Lambda function

Resources:
  RouterLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./backend/lambda/
      Handler: app.lambda_handler
      Runtime: python3.12
      Timeout: 30

  FEApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      DefinitionBody:
        openapi: 3.0.0
        info:
          title: Frontend API
          version: 1.0.0
        paths:
          /hello:
            get:
              x-amazon-apigateway-integration:
                httpMethod: GET
                payloadFormatVersion: 2.0
                type: aws_proxy
                uri: !GetAtt RouterLambda.Arn
          /recruitmentRounds:
            get:
              x-amazon-apigateway-integration:
                httpMethod: GET
                payloadFormatVersion: 2.0
                type: aws_proxy
                uri: !GetAtt RouterLambda.Arn

Outputs:
  ApiUrl:
    Description: API endpoint URL for Prod environment
    Value: !Sub 'https://${FEApi}.execute-api.${AWS::Region}.amazonaws.com/prod'